quaver_time:
  value_class: integer
  default: 110
  display_name: "Quaver Time"
  description: "The number of milliseconds for each quaver of music"

wait_steps:
  value_class: integer
  default: 3
  display_name: "Wait steps"
  description: "After placing a note a count-down from this number will take place"

wait_step_time:
  value_class: integer
  default: 500
  display_name: "Wait Step Time"
  description: "Each number in the count down will take this many milliseconds"
